#!/usr/bin/env bash

sudo apt-get update
sudo apt-get -y install nginx

mkdir -p /data/
mkdir -p /data/web_static/
mkdir -p /data/web_static/releases/
mkdir -p /data/web_static/shared/
touch /data/web_static/releases/test/index.html

content='Hello world!'
echo "$content" > /data/web_static/releases/test/index.html
ln -sf /data/web_static/releases/test/ /data/web_static/current
chown -R ubuntu:ubuntu /data/

config="server {
»·······listen 80 default_server;
»·······listen [::]:80 default_server;
	location /hbnb_static {
		alias /data/web_static/current;
	}
}"

echo -e "$config" > /etc/nginx/sites-enabled/default
sudo service nginx restart
